# Configuration file for the project

gcs_bucket_name: dm_graphcast

model_file_name: >
  params/GraphCast_small - ERA5 1979-2015 - resolution 1.0 - pressure levels 13 - mesh 2to5 - precipitation input and output.npz

dataset_file_name: >
  dataset/source-era5_date-2022-01-01_res-0.25_levels-13_steps-01.nc

normalization_files:
  diffs_stddev_by_level: stats/diffs_stddev_by_level.nc
  mean_by_level: stats/mean_by_level.nc
  stddev_by_level: stats/stddev_by_level.nc

train_steps: 1
eval_steps_offset: 2 # Number of time steps to exclude from evaluation
random_seed: 0
